[package]
authors = ["Adrian Perez de Castro <aperez@igalia.com>"]
name = "chippers"
version = "0.1.0"

[dependencies]
bitflags = "*"
clap = "*"

[dependencies.nom]
version = "*"
features = ["verbose-errors"]
